"""Removed theme from support token

Revision ID: 23196adc7075
Revises: 25a93ff9bb02
Create Date: 2025-05-07 23:07:19.369303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23196adc7075'
down_revision = '25a93ff9bb02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_tokens', schema=None) as batch_op:
        batch_op.drop_column('theme')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme', sa.VARCHAR(length=64), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
