"""Renaming

Revision ID: 25a93ff9bb02
Revises: c077b91accc7
Create Date: 2025-05-05 22:59:56.035321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25a93ff9bb02'
down_revision = 'c077b91accc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playoff_stage_matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bracket', sa.String(length=8), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
        batch_op.drop_column('admin_role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_role', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('playoff_stage_matches', schema=None) as batch_op:
        batch_op.drop_column('bracket')

    # ### end Alembic commands ###
