"""Added number to Match

Revision ID: 3319046a1ba2
Revises: 447cce2f6b59
Create Date: 2025-05-14 13:46:52.149832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3319046a1ba2'
down_revision = '447cce2f6b59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number', sa.String(length=4), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_column('number')

    # ### end Alembic commands ###
