"""Added description and contact to Tournament

Revision ID: 447cce2f6b59
Revises: 4e58e4f46e01
Create Date: 2025-05-13 20:01:39.580802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '447cce2f6b59'
down_revision = '4e58e4f46e01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('contact', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.drop_column('contact')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
