"""Renamed MAP external_id -> external_url

Revision ID: ae6e36f1bd0c
Revises: 003bb8e5b24f
Create Date: 2025-05-10 01:00:28.833595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae6e36f1bd0c'
down_revision = '003bb8e5b24f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_url', sa.String(length=128), nullable=True))
        batch_op.drop_column('external_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
        batch_op.drop_column('external_url')

    # ### end Alembic commands ###
