"""Renamed prize_pool to prize_fund

Revision ID: c077b91accc7
Revises: 2efa9d2fcbd2
Create Date: 2025-05-04 22:19:57.817220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c077b91accc7'
down_revision = '2efa9d2fcbd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled_time', sa.DateTime(), nullable=True))

    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prize_fund', sa.String(length=8), nullable=True))
        batch_op.drop_column('prize_pool')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prize_pool', sa.VARCHAR(length=8), autoincrement=False, nullable=True))
        batch_op.drop_column('prize_fund')

    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_column('scheduled_time')

    # ### end Alembic commands ###
