"""Added highlight_url

Revision ID: dba3ae5b1fb9
Revises: ef83a0299062
Create Date: 2025-06-05 20:46:44.775578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dba3ae5b1fb9'
down_revision = 'ef83a0299062'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connections', schema=None) as batch_op:
        batch_op.drop_constraint('connections_external_user_url_key', type_='unique')

    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('highlight_url', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.drop_column('highlight_url')

    with op.batch_alter_table('connections', schema=None) as batch_op:
        batch_op.create_unique_constraint('connections_external_user_url_key', ['external_user_url'])

    # ### end Alembic commands ###
