"""Changed capacity of job_id

Revision ID: ef83a0299062
Revises: 0140157ec6cb
Create Date: 2025-05-17 17:53:24.078688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef83a0299062'
down_revision = '0140157ec6cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_tournaments', schema=None) as batch_op:
        batch_op.alter_column('job_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=256),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_tournaments', schema=None) as batch_op:
        batch_op.alter_column('job_id',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
